version: '3.4'
services:
  testapi:
    image: ${DOCKER_REGISTRY-}testapi
    build:
      context: .
      dockerfile: testApi/Dockerfile
    ports:
        - "8080:80"
    depends_on:
        - db
  db:
    image: "jschec/patient-demo-db-mssql:patient-db"
    ports:
        - "1433:1433"
    environment:
        SA_PASSWORD: "testDBpass1234!"
        ACCEPT_EULA: "Y"